name: Build Disk Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      IMAGE_NAME: clarityos
      IMAGE_REPO: ghcr.io/clarityos/image
      IMAGE_TAG: latest
      VARIANT: main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Grab full version from container image
        id: get_version
        run: |
          FULL_VERSION=$(podman run --rm ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }} \
            cat /usr/share/ublue-os/image-info.json | jq -r '.version')
          MAJOR_VERSION="${FULL_VERSION%%.*}"
          echo "Full version: $FULL_VERSION"
          echo "Major version: $MAJOR_VERSION"
          echo "major_version=$MAJOR_VERSION" >> $GITHUB_OUTPUT

      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: ${{ env.ARCH }}
          image_name: ${{ env.IMAGE_NAME }}
          image_repo: ${{ env.IMAGE_REPO }}
          image_tag: ${{ env.IMAGE_TAG }}
          version: ${{ steps.get_version.outputs.major_version }}
          variant: ${{ env.VARIANT }}
          iso_name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ steps.get_version.outputs.major_version }}.iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
